[package]
name = "tinydns"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
influxdb = "0.7.2"
log = "0.4"
env_logger = "0.11.6"
log-execution-time = "0.1.0"
